spring:
  application:
    name: project1
  profiles:
    active:
    - dev
  config:
    import:
    - optional:configserver:http://localhost:8888
#  cloud:
#    config:
#      uri:
#      - http://localhost:8888

server:
  port: 8081